#!/bin/bash

# a wrapper script to run the unit-tests. On the host it shall setup a one node
# vagrant environment and trigger the unit tests in the sandbox vm. This is
# needed since some unit-tests depend on the external daemon like ovs, etcd
# etc to be setup.

test_packages="github.com/contiv/netplugin/drivers \
    github.com/contiv/netplugin/state \
    github.com/contiv/netplugin/plugin \
    github.com/contiv/netplugin/netutils \
    github.com/contiv/netplugin/crt \
    github.com/contiv/netplugin/gstate \
    github.com/contiv/netplugin/netmaster/master \
    github.com/contiv/netplugin/netmaster/client \
    github.com/contiv/netplugin/resources \
    github.com/contiv/netplugin/core \
    github.com/contiv/netplugin/utils \
    "

while [ "${#}" -gt 0 ]
do
  echo "This program requires no arguments."
  exit 1
done

for pkg in ${test_packages}
do
  # running in the sand box
  (cd $GOSRC/github.com/contiv/netplugin && \
  godep go test ${pkg}) || exit 1
done

echo "Sandbox: Tests succeeded!"
exit 0
